version: "3"

services:
  web_serv:
    build: .
    environment:
      DB_HOST: db
      PORT: 80
    ports:
      - "80:80"
  db:
    image: mysql
    volumes:
      - .:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: meow
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80